[package]
name = "llm-proxy"
version = "0.1.2"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bytes = "1.12.1"
converter = { git = "ssh://git@github.com/WenChunTech/converter.git", branch = "master" }
futures-util = "0.3.32"
mime_guess = "2.0.5"
reqwest = { version = "0.13.4", features = ["json", "stream", "rustls", "form"] }
rust-embed = "8.12.0"
salvo = { version = "0.95.0", features = ["sse", "cors", "timeout", "logging"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
tokio = { version = "1.52.4", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }

[dev-dependencies]
serde_json = "1.0.150"
tokio = { version = "1.52.4", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.13.4", features = ["json", "rustls"] }
